enum GlobalStateActions {
	SET_STRETCH_ROUTINE,
	SET_CARDS,
	SET_CARD_SHOWN_ID,
	SET_LAST_CARD_ID,
	SET_STRETCH_COMPLETE,
	SET_STRETCH_INCOMPLETE,
	RESET_STRETCHES,
	SET_MEDITATION_ROUTINE,
}

export default GlobalStateActions;
